clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: Heroku Staging Deployement
          deployment: master
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

    #master:
    #  - step:
    #      name: Heroku Production Deployment
    #      deployment: production
    #      script:
    #        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME_PROD.git HEAD
